FROM node:13.8-alpine AS builder
WORKDIR /apollon

RUN apk add git && \ 
    npm install -g nodemon bunyan 

COPY package.json package.json
RUN npm i

ENV LOG_LEVEL DEBUG
ENV APOLLON_ENV development

ENTRYPOINT ["npm", "run", "nodemon"]
